name: Create release PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    #   Let's try to trigger releases only after this release PR gets merged
    # so we might need to verify who the author is to do so
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node
          skip-github-release: true
          skip-labeling: true